#!/bin/bash
full=$(df --output=pcent /LOG | sed -n 2p | awk '{print $1}' |  sed 's/[^0-9]*//g')
if [ $full -ge 70 ]
then
sudo tar --exclude='/LOG/lost+found' -rvf /BACKUP/archive.tar /LOG/*
cd /LOG
ls /LOG|grep -v lost+found|sudo xargs rm -rfv
fi

